#!/usr/bin/env sh

[ ! -f "$(dirname -- "$0")/_/husky.sh" ] && exit 0
[ -n "$CI" ] || [ -n "$NETLIFY" ] && exit 0

. "$(dirname -- "$0")/_/husky.sh"

echo "post-checkout: diff $1 $2"

ABIS_CHANGED=`git diff $1 $2 --stat -- $0/src/constants/abi/**/*.json | wc -l`
if [ $ABIS_CHANGED -gt 0 ];
then
  echo "post-checkout: abis have changed, running typechain"
  yarn run generate:typechain
else
  echo "post-checkout: no abi changes"
fi

GQLS_CHANGED=`git diff $1 $2 --stat -- $0/src/**/*.graphql | wc -l`
if [ $GQLS_CHANGED -gt 0 ];
then
  echo "post-checkout: gql queries have changed, running generator"
  yarn run generate:graphql
else
  echo "post-checkout: no gql changes"
fi