/** Declaration file generated by dts-gen */

export = segment_js;

declare class segment_js {
  constructor(path: any, begin: any, end: any, circular: any);

  draw(begin: any, end: any, duration: any, options: any): any;

  drawStep(t: any): void;

  pause(): void;

  percent(value: any): any;

  play(): any;

  reset(): void;

  resume(): void;

  stop(): void;

  strokeDasharray(begin: any, end: any): any;

  valueOf(input: any): any;
}
