#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

# Exit if in CI
[ -n "$CI" ] || [ -n "$NETLIFY" ] && exit 0

# TODO: automatically detect if yarn.lock/package.json changed and run yarn
# TODO: auomatically run yarn generate if /protocol changed abi
echo "Changes pulled. Maybe run yarn, and/or yarn generate"
exit 0