name: Wells SDK

on:
  pull_request:
    types: [opened, synchronize]
    paths:
      - "projects/sdk-wells/**"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: SDK Wells Tests
        uses: actions/setup-node@v3
        with:
          node-version: "16"
      - name: Cache Node Modules
        id: node-modules-cache
        uses: actions/cache@v3
        with:
          path: "**/node_modules"
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}
      - name: Install Dependencies
        if: steps.node-modules-cache.outputs.cache-hit != 'true'
        run: yarn install --immutable
      - name: Generate Typedefs
        run: yarn sdk:generate
      - name: Install Rust (Stable)
        run: curl https://sh.rustup.rs -sSf | sh -s -- -y
      - name: Install Anvil
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly
      - name: Launch Anvil
        run: anvil --fork-url $ANVIL_FORK_URL --chain-id 1337 &
        env:
          ANVIL_FORK_URL: ${{ secrets.ANVIL_FORK_URL }}
      - name: Build All
        run: yarn build
      - name: Run Tests
        run: yarn sdk-wells:test
        working-directory: projects/sdk-wells
